name: dev-docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Build River
        uses: ./.github/actions/install-env
        with:
          build-root: false
          python-version: '3.12'
      - name: Install extra Ubuntu dependencies
        run: sudo apt-get install graphviz pandoc
      - id: measurement-4
        name: Record Measurement After Install extra Ubuntu dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install extra Ubuntu dependencies
          task: get-measurement
      - name: Install extra Python dependencies
        run: 'poetry install --with docs

          '
      - id: measurement-6
        name: Record Measurement After Install extra Python dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install extra Python dependencies
          task: get-measurement
      - name: Build docs
        run: 'source $VENV

          make doc

          '
      - id: measurement-8
        name: Record Measurement After Build docs
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build docs
          task: get-measurement
      - env:
          GH_TOKEN: ${{ secrets.GitHubToken }}
        name: Deploy docs
        run: 'source $VENV

          git config user.name github-actions

          git config user.email github-actions@github.com

          git config pull.rebase false

          git add --all

          git commit -m "Release dev docs" --allow-empty

          git fetch

          git checkout gh-pages

          git pull

          git checkout main

          mike deploy dev --push --remote https://github.com/${{ github.repository
          }}.git

          '
      - id: measurement-10
        name: Record Measurement After Deploy docs
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Deploy docs
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
